### ISSUE TITLE
TODO digit_recognition

### ISSUE THREAD

**Issue by tzch96** [tzch96/digit_recognition#1]
- [ ] Get the accuracy to over 95%
- [ ] Explore other activation functions and parameter values
- [ ] Make it possible for the user to input their own number and ask the program to classify it
